state_map={
    'Jammu And Kashmir':['Vaishno Devi','Sri Shankaracharya Temple','Wadiy e Hajan','Tulip Garden Srinagar','Shah Kashmir Arts Emporium','hri Amarnath Cave Temple','Sinthan Top','Dal Lake','Shalimar Bagh Mughal Garden','Nigeen Lake'],
    'Himachal Pradesh' :['Shimla','Kullu-Manali','Dharamshala and McLeodganj','Dalhousie','Khajjiar','Kasol','Kasauli','Kufri','Palampur','Kangra'],
    'Panjab' : ['Amritsar','Ludhiana','Jalandhar','Bathinda'],
    'Nepal' : ['Bhaktapur','Chitwan National Park','Lumbini','Pokhara','Kathmandu'],
    'Delhi' : ['Chandni Chowk','Hauz Khas','Qutab Minar','Red Fort','India Gate'],
    'Uttarakhand' : ['Harsil','Munsiyari','Utha','Chakrata','Mussoorie','Nainital','Auli'],
    'Rajasthaan' : ['Ranthambore Tiger Reserve','City Palace of Jaipur','Hawa Mahal - Palace of Wind','Lake Pichola','City Palace of Udaipur','Elefantastic','Mehrangarh Fort'],
    'Uttar Pradesh' : ['Taj Mahal','Wildlife Sos','Assi Ghat','Agra Fort'],
    'Bihar' : ['Kesaria','Pawanpuri','Rajgir','Vaishali','Nalanda','Bodhgaya'],
    'West Bengal' : ['Kurseong','Kalimpong','Dooars','Mirik','Siliguri','Sundarbans','Darjeeling','Kolkata'],
    'Jharkhand' : ['Dhanbad','Deoghar','Jamshedpur','Ranchi'],
    'Chhattisgarh' : ['Chitrakote Falls','Madku Dweep','Mainpat','Charre Marre Waterfalls','Jagdalpur','Barnawapara Wildlife Sanctuary'],
    'Madhya Pradesh' : ['Gwalior','Pachmarhi','Khajuraho','Rajwada Palace','Bhimbetka rock shelters','Kanha Tiger Reserve','Bhedaghat'],
    'Gujarat' : ['Somnath Temple','Laxmi Vilas Palace','Adalaj Stepwell','Sabarmati Ashram','Shree Dwarkadhish Temple','Gir National Park','Statue Of Unity'],
    'Maharashtra' : ['Malshej Ghat','Chhatrapati Shivaji Maharaj Terminus','Ajanta Caves','Ellora Caves','Gateway Of India Mumbai','Fort Raigad','Tadoba-Andhari Tiger Reserve'],
    'Odisha' : ['Bhitarkanika National Park','Udayagiri','Chilika Lake','Konark','Bhubaneswar','Puri'],
    'Telungana' : ['Nizamabad','Nalgonda','Adilabad','Bhadrachalam','Warangal','Nagarjunasagar','Hyderabath'],
    'Andhara Pradesh' : ['Vijayawada','Tirupati','Gandikota','Amaravathi','Visakhapatnam','Araku Valley'],
    'Karnataka' : ['Chikmagalur','Jog Falls','Udupi','Gokarna','Hampi','Badami','Coorg'],
    'Kerala' : ['Idukki','Kollam','Poovar','Kovalam','Vagamon','Varkala','Wayanad','Kochi','Munnar'],
    'Tamil Nadu' : ['Kolli Malai','Kutralam','Yelagiri','Velankanni','Coonoor','Mahabalipuram','Hogenakkal','Ooty','Kodaikanal','Yercaud'],
    'Arunachal Pradesh' : ['Roing','Tezu','Sela Pass','Namdapha National Park','Ziro Valley','Tawang'],
    'Assam' : ['Dibrugarh','Manas National Park','Jorhat','Guwahati','Majuli'],
    'Nagaland' : ['Pfutsero','Khonoma Village','Tuensang','Kohima'],
    'Manipur' : ['Tamenglong','Thoubal','Chandel','Khongjom','Andro'],
    'Mizoram' : ['Reiek Tlang','Champhai','Lunglei']
}