def get_donors(district, city, blood_type):
    # This is a placeholder. You should replace this with your actual data retrieval logic.
    # The structure of donors should be a list of dictionaries with 'name' and 'contact' keys.
    if district == 'Maharashtra':
        if city == '':

            if blood_type == 'Hotel':
                donors = [
                    {'name': 'Blu Water Resort Malshej'},
                    {'name': 'Saj By The Lake: Luxury Resort'},
                    {'name': 'MTDC Resort'}
                    # Add more donors as needed
                ]
            
        if city == 'Chhatrapati Shivaji Maharaj Terminus':


            if blood_type == 'Hotel':
                donors = [
                    {'name': 'West End Hotel'},
                    {'name': ' Empire Royale Hotel '},
                    
                    # Add more donors as needed
                ]
        if city == 'Ajanta Caves':

            if blood_type == 'Hotel':
                donors = [
                    {'name': 'Hotel Royal Ajanta Park'},
                    {'name': 'Agrawals restaurant and lodging'},
                    {'name': 'Hotel ajanta green restaurant '}
                    # Add more donors as needed
                ]
        if city == 'Ellora Caves':

            if blood_type == 'Hotel':
                donors = [
                    {'name': 'Hotel Kailas'},
                    {'name': 'Ellora Heritage Resort'}
                    # Add more donors as needed
                ]
        if city == 'Gateway Of India Mumbai':

            if blood_type == 'Hotel':
                donors = [
                    {'name': 'Hotel Grace galaxy'},
                    {'name': 'The Royal Orchid'},
                    {'name': 'Empire Royale Hotel'}
                    # Add more donors as needed
                ]
        if city == 'Fort Raigad':

            if blood_type == 'Hotel':
                donors = [
                    {'name': 'Hotel Jay bhavani farm house raigad fort'},
                    {'name': 'Sahyadri hotel'},
                    {'name': 'Hirkani Aangan'}
                    # Add more donors as needed
                ]
        if city == 'Tadoba-Andhari Tiger Reserve':

            if blood_type == 'Hotel':
                donors = [
                    {'name': 'Avadale Tadoba'},
                    {'name': 'Tadoba Tiger Valley Resort'},
                    {'name': 'Hotel Tiger Inn'}
                    # Add more donors as needed
                ]
                    
                    
                    
                
                    
                    
                        
            